# Generated by Django 5.1.5 on 2025-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('difficulty', models.CharField(max_length=6)),
                ('dislikes', models.IntegerField()),
                ('exampleTestcaseList', models.JSONField()),
                ('hints', models.JSONField()),
                ('isPaidOnly', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('questionId', models.IntegerField(unique=True)),
                ('stats', models.JSONField()),
                ('title', models.CharField(max_length=128)),
                ('titleSlug', models.CharField(max_length=128)),
                ('codeSnippets', models.JSONField(default=dict)),
                ('similarQuestionList', models.JSONField()),
                ('topicTags', models.JSONField()),
                ('url', models.CharField(max_length=256)),
                ('personalDifficulty', models.FloatField(default=5.0)),
                ('lastSolved', models.DateTimeField(blank=True, null=True)),
                ('solvedCount', models.IntegerField(default=0)),
                ('relatedProblems', models.ManyToManyField(blank=True, to='problem.problem')),
                ('topics', models.ManyToManyField(blank=True, related_name='problems', to='problem.topic')),
            ],
            options={
                'ordering': ['questionId'],
            },
        ),
    ]
