# Generated by Django 5.1.5 on 2025-02-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_taken', models.IntegerField()),
                ('failed_attempts', models.IntegerField()),
                ('failed_test_cases', models.JSONField()),
                ('failed_submissions', models.JSONField()),
                ('solution', models.JSONField()),
                ('personal_difficulty', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='personalDifficulty',
        ),
        migrations.AlterField(
            model_name='problem',
            name='codeSnippets',
            field=models.JSONField(),
        ),
    ]
